# Generated by Django 3.2 on 2023-12-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_rating'),
        ('reviews', '0002_auto_20231221_1607'),
    ]

    operations = [
    ]
