# Generated by Django 3.2 on 2023-12-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20231213_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for_title', to='reviews.title', verbose_name='Отзыв'),
            preserve_default=False,
        ),
    ]
