# Generated by Django 3.2 on 2023-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(null=True),
        ),
    ]
