# Generated by Django 3.2 on 2023-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_auto_20231216_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(default=1),
        ),
    ]
